const links = [
  "https://home.hamusata.f5.si/",
  "https://hamuzon.github.io/Time-Zone_app/",
  "https://pw.link-s.f5.si/",
  "https://scratch.hamusata.f5.si/",
  "https://hamuzon.github.io/expo2025-counter/",
  "https://link-s.f5.si/",
  "https://time.hamusata.f5.si",
  "https://hamuzon.github.io/binary-decimal-converter/",
  "https://go.link-s.f5.si/",
  "https://Device-info.hamusata.f5.si",
  "https://hamuzon.github.io/Device-info/",
  "https://password-create.link-s.f5.si/",
  "https://expo2025-counter.hamusata.f5.si",
  "https://hamuzon.github.io/text/",
  "https://password.link-s.f5.si/",
  "https://bin2dec.hamusata.f5.si",
  "https://hamuzon.github.io/Calculator/",
  "https://pw-pc.link-s.f5.si/",
  "https://text.hamusata.f5.si",
  "https://hamuzon.github.io/password/",
  "https://pw-sp.link-s.f5.si/",
  "https://Calculator.hamusata.f5.si",
  "https://hamuzon.github.io/calendar/",
  "https://qr.link-s.f5.si/",
  "https://password-create.hamusata.f5.si",
  "https://hamuzon.github.io/todo/",
  "https://link.hamusata.f5.si",
  "https://calendar.hamusata.f5.si",
  "https://hamuzon.github.io/QR/",
  "https://todo.hamusata.f5.si",
  "https://hamuzon.github.io/omikuji/",
  "https://url.hamusata.f5.si",
  "https://hamuzon.github.io/dice/",
  "https://qr.hamusata.f5.si",
  "https://hamuzon.github.io/Short-Link/",
  "http://omikuji.hamusata.f5.si",
  "https://hamuzon.github.io/pixel-art/",
  "https://dice.hamusata.f5.si",
  "https://pixel-art.hamusata.f5.si/",
  "./"
];

function openRandomLink() {
  const randomIndex = Math.floor(Math.random() * links.length);
  window.open(links[randomIndex], "_blank");
}