const links = [
"https://home.hamusata.f5.si/",
"https://hamusata.f5.si/",
"https://scratch.hamusata.f5.si/",
"https://time.hamusata.f5.si",
"https://time-zone.hamusata.f5.si",
"https://Device-info.hamusata.f5.si",
"https://expo2025-counter.hamusata.f5.si",
"https://bin2dec.hamusata.f5.si",
"https://text.hamusata.f5.si",
"https://Calculator.hamusata.f5.si",
"https://password-create.hamusata.f5.si",
"https://calendar.hamusata.f5.si",
"https://todo.hamusata.f5.si",
"https://url.hamusata.f5.si",
"https://link.hamusata.f5.si",
"https://qr.hamusata.f5.si",
"http://omikuji.hamusata.f5.si",
"https://dice.hamusata.f5.si",
"https://pixel-art.hamusata.f5.si/",
"https://editor.hamusata.f5.si/",
"https://world.hamusata.f5.si/",
"https://pw.hamusata.f5.si/",
"https://pw-sp.hamusata.f5.si/",
"https://pw-pc.hamusata.f5.si/",

"https://hamuzon.github.io/Time-Zone_app/",
"https://hamuzon.github.io/expo2025-counter/",
"https://hamuzon.github.io/binary-decimal-converter/",
"https://hamuzon.github.io/Device-info/",
"https://hamuzon.github.io/text/",
"https://hamuzon.github.io/Calculator/",
"https://hamuzon.github.io/password/",
"https://hamuzon.github.io/calendar/",
"https://hamuzon.github.io/todo/",
"https://hamuzon.github.io/QR/",
"https://hamuzon.github.io/omikuji/",
"https://hamuzon.github.io/dice/",
"https://hamuzon.github.io/Short-Link/",
"https://hamuzon.github.io/pixel-art/",
"https://hamuzon.github.io/editor/",

"https://link-s.f5.si/",
"https://go.link-s.f5.si/",
"https://password-create.link-s.f5.si/",
"https://password.link-s.f5.si/",
"https://pw.link-s.f5.si/",
"https://pw-pc.link-s.f5.si/",
"https://pw-sp.link-s.f5.si/",
"https://qr.link-s.f5.si/",

"https://hamuzon.web.fc2.com/password/",
"https://hamuzon.web.fc2.com/time/",
"https://hamuzon.web.fc2.com/bin2dec/",
"https://hamuzon.web.fc2.com/calculator/",
"https://hamuzon.web.fc2.com/website-list/",
"https://hamuzon.web.fc2.com/tanzaku/",
"https://hamuzon.web.fc2.com/calendar/",
"https://hamuzon.web.fc2.com/video/",
"https://hamuzon.web.fc2.com/todo/",
"https://hamuzon.web.fc2.com/task-board/",
"https://hamuzon.web.fc2.com/qr/",
"https://hamuzon.web.fc2.com/birthday/",
"https://hamuzon.web.fc2.com/url/",
"https://hamuzon.web.fc2.com/discord/",
"https://hamuzon.web.fc2.com/text/",
"https://hamuzon.web.fc2.com/fraction/",
"https://hamuzon.web.fc2.com/expo/",
"https://hamuzon.web.fc2.com/editor/",

"https://hamuzon-jp.f5.si/Time-Zone_app/",
"https://hamuzon-jp.f5.si/expo2025-counter/",
"https://expo.hamuzon-jp.f5.si/",
"https://hamuzon-jp.f5.si/clock/",
"https://hamuzon-jp.f5.si/bin2dec/",
"https://hamuzon-jp.f5.si/text/",
"https://hamuzon-jp.f5.si/Device-info/",
"https://hamuzon-jp.f5.si/password/",
"https://hamuzon-jp.f5.si/calculator/",
"https://hamuzon-jp.f5.si/calendar/",
"https://hamuzon-jp.f5.si/todo/",
"https://hamuzon-jp.f5.si/task-board/",
"https://hamuzon-jp.f5.si/birthday/",
"https://hamuzon-jp.f5.si/qr/",
"https://hamuzon-jp.f5.si/dice/",
"https://hamuzon-jp.f5.si/omikuji/",
"https://hamuzon-jp.f5.si/passapi/",
"https://hamuzon-jp.f5.si/discord/",
"https://hamuzon-jp.f5.si/fraction/",
"https://hamuzon-jp.f5.si/pixel-art/",
"https://hamuzon-jp.f5.si/editor/",
"https://world.hamuzon-jp.f5.si/",
"https://pc.hamuzon-jp.f5.si/",
"https://pw-sp.hamuzon-jp.f5.si/",
"https://pw-pc.hamuzon-jp.f5.si/",

];

function openRandomLink() {
const randomIndex = Math.floor(Math.random() * links.length);
window.open(links[randomIndex], "_blank");
}
